#pragma once

#define IDI_APP_ICON                    1

#define IDS_APP_TITLE                   100
#define IDS_LANGUAGE                    101
#define IDS_LANGUAGE_CHINESE            102
#define IDS_LANGUAGE_ENGLISH            103
#define IDS_STATUS_READY                104
#define IDS_STATUS_CONNECTING           105
#define IDS_STATUS_MISSING              106
#define IDS_STATUS_UPDATE               107
#define IDS_STATUS_UNAVAILABLE          108
#define IDS_STATUS_READY_DESC           109
#define IDS_STATUS_CONNECTING_DESC      110
#define IDS_STATUS_MISSING_DESC         111
#define IDS_STATUS_UPDATE_DESC          112
#define IDS_STATUS_UNAVAILABLE_DESC     113
#define IDS_RETRY                       114
#define IDS_PERFORMANCE_MODE            115
#define IDS_QUIET                       116
#define IDS_PERFORMANCE                 117
#define IDS_APPLY                       118
#define IDS_PROFILE_HINT                119
#define IDS_COOLING                     120
#define IDS_AUTOMATIC                   121
#define IDS_FULL_SPEED                  122
#define IDS_MANUAL                      123
#define IDS_FAN_SPEED                   124
#define IDS_FAN_HINT                    125
#define IDS_TEMPERATURES                126
#define IDS_POWER                       127
#define IDS_USB_C_1                     128
#define IDS_USB_C_2                     129
#define IDS_SYSTEM_TOTAL                130
#define IDS_NOT_AVAILABLE               131
#define IDS_APPLIED                     132
#define IDS_ACTION_FAILED               133
#define IDS_CONFIRM_TITLE               134
#define IDS_CONFIRM_PROFILE             137
#define IDS_PERCENT_FORMAT              138
#define IDS_TEMPERATURE_FORMAT          139
#define IDS_POWER_FORMAT                140
#define IDS_ELECTRICAL_FORMAT           141
#define IDS_CLOSE_PENDING               142
#define IDS_CPU                         143
#define IDS_GPU                         144

#define IDC_TITLE                       1000
#define IDC_LANGUAGE                    1001
#define IDC_STATUS_TITLE                1002
#define IDC_STATUS_DESC                 1003
#define IDC_RETRY                       1004
#define IDC_PROFILE_HEADING             1010
#define IDC_PROFILE_QUIET               1011
#define IDC_PROFILE_PERFORMANCE         1012
#define IDC_PROFILE_APPLY               1013
#define IDC_PROFILE_HINT                1014
#define IDC_FAN_HEADING                 1020
#define IDC_FAN_MODE                    1021
#define IDC_FAN_SLIDER                  1022
#define IDC_FAN_PERCENT                 1023
#define IDC_FAN_APPLY                   1024
#define IDC_FAN_HINT                    1025
#define IDC_TEMP_HEADING                1030
#define IDC_TEMP1_LABEL                 1031
#define IDC_TEMP1_VALUE                 1032
#define IDC_TEMP2_LABEL                 1033
#define IDC_TEMP2_VALUE                 1034
#define IDC_POWER_HEADING               1040
#define IDC_POWER1_LABEL                1041
#define IDC_POWER1_VALUE                1042
#define IDC_POWER1_DETAIL               1043
#define IDC_POWER2_LABEL                1044
#define IDC_POWER2_VALUE                1045
#define IDC_POWER2_DETAIL               1046
#define IDC_POWER_SYSTEM_LABEL          1047
#define IDC_POWER_SYSTEM_VALUE          1048
#define IDC_POWER_SYSTEM_DETAIL         1049
#define IDC_NOTICE                      1050

#define IDM_LANGUAGE_CHINESE            40001
#define IDM_LANGUAGE_ENGLISH            40002
