/*++

Copyright (c) 2026 Radxa Computer Co., Ltd.

Public user/kernel ABI for the Radxa SVC service hosted by radxaplatform.sys.
The GLINK wire protocol is intentionally not exposed through this header.

--*/

#pragma once

#if defined(_KERNEL_MODE) || defined(USE_IN_KERNEL_MODE)
#include <ntddk.h>
#include <devioctl.h>
#else
#include <Windows.h>
#include <winioctl.h>
#endif

#ifndef RADXA_PLATFORM_TYPE
#define RADXA_PLATFORM_TYPE 40000
#endif

#define RADXA_SVC_DEVICE_PATH                 L"\\\\.\\RadxaPlatform"
#define RADXA_SVC_USER_API_VERSION            1u
#define RADXA_SVC_MAX_LOG_SIZE                2048u
#define RADXA_SVC_MAX_SENSORS                 64u
#define RADXA_SVC_SENSOR_NAME_LENGTH          32u

/* Service capabilities returned by GET_SERVICE_VERSION. */
#define RADXA_SVC_CAP_PING                    0x00000001u
#define RADXA_SVC_CAP_PROFILE                 0x00000002u
#define RADXA_SVC_CAP_LOG                     0x00000004u
#define RADXA_SVC_CAP_PWM                     0x00000010u
#define RADXA_SVC_CAP_FANCTL                  0x00000020u
#define RADXA_SVC_CAP_FANCTL_CTRL             0x00000040u
#define RADXA_SVC_CAP_SENSORS                 0x00000080u
#define RADXA_SVC_CAP_EMI                     0x00000100u

#define RADXA_SVC_REQUIRED_CAPABILITIES       \
    (RADXA_SVC_CAP_PROFILE | RADXA_SVC_CAP_FANCTL | RADXA_SVC_CAP_FANCTL_CTRL)

/* RADXA_SVC_INTERFACE_INFO.State values. */
#define RADXA_SVC_STATE_UNAVAILABLE           0u
#define RADXA_SVC_STATE_GLINK_INTERFACE       1u
#define RADXA_SVC_STATE_LINK_UP               2u
#define RADXA_SVC_STATE_CHANNEL_CONNECTED     3u
#define RADXA_SVC_STATE_READY                 4u
#define RADXA_SVC_STATE_INCOMPATIBLE_VERSION  5u
#define RADXA_SVC_STATE_MISSING_CAPABILITIES  6u
#define RADXA_SVC_STATE_HANDSHAKE_FAILED      7u
#define RADXA_SVC_STATE_SHUTTING_DOWN         8u

#define RADXA_SVC_PROFILE_QUIET               0u
#define RADXA_SVC_PROFILE_PERFORMANCE         1u
#define RADXA_SVC_PROFILE_CUSTOM              2u

#define RADXA_SVC_FAN_CONTROL_FULL_SPEED      0u
#define RADXA_SVC_FAN_CONTROL_MANUAL          1u
#define RADXA_SVC_FAN_CONTROL_AUTO            2u
#define RADXA_SVC_FAN_PWM_MAX                 255u

#define RADXA_SVC_SENSOR_TEMPERATURE          1u
#define RADXA_SVC_SENSOR_VOLTAGE              2u
#define RADXA_SVC_SENSOR_CURRENT              3u
#define RADXA_SVC_SENSOR_VOLTAGE_CURRENT      4u

#define RADXA_SVC_SENSOR_VALID_TEMPERATURE    0x00000001u
#define RADXA_SVC_SENSOR_VALID_VOLTAGE        0x00000002u
#define RADXA_SVC_SENSOR_VALID_CURRENT        0x00000004u

#define IOCTL_RADXA_PLATFORM_SVC_GET_INTERFACE_INFO \
    CTL_CODE(RADXA_PLATFORM_TYPE, 0xA40, METHOD_BUFFERED, FILE_READ_ACCESS)
#define IOCTL_RADXA_PLATFORM_SVC_PING \
    CTL_CODE(RADXA_PLATFORM_TYPE, 0xA41, METHOD_BUFFERED, FILE_READ_ACCESS)
#define IOCTL_RADXA_PLATFORM_SVC_GET_SERVICE_VERSION \
    CTL_CODE(RADXA_PLATFORM_TYPE, 0xA42, METHOD_BUFFERED, FILE_READ_ACCESS)
#define IOCTL_RADXA_PLATFORM_SVC_GET_PROFILE \
    CTL_CODE(RADXA_PLATFORM_TYPE, 0xA43, METHOD_BUFFERED, FILE_READ_ACCESS)
#define IOCTL_RADXA_PLATFORM_SVC_SET_PROFILE \
    CTL_CODE(RADXA_PLATFORM_TYPE, 0xA44, METHOD_BUFFERED, FILE_WRITE_ACCESS)
#define IOCTL_RADXA_PLATFORM_SVC_GET_LOG \
    CTL_CODE(RADXA_PLATFORM_TYPE, 0xA45, METHOD_BUFFERED, FILE_READ_ACCESS)
#define IOCTL_RADXA_PLATFORM_SVC_PWM_GET_INFO \
    CTL_CODE(RADXA_PLATFORM_TYPE, 0xA46, METHOD_BUFFERED, FILE_READ_ACCESS)
#define IOCTL_RADXA_PLATFORM_SVC_PWM_APPLY \
    CTL_CODE(RADXA_PLATFORM_TYPE, 0xA47, METHOD_BUFFERED, FILE_WRITE_ACCESS)
#define IOCTL_RADXA_PLATFORM_SVC_PWM_GET_STATE \
    CTL_CODE(RADXA_PLATFORM_TYPE, 0xA48, METHOD_BUFFERED, FILE_READ_ACCESS)
#define IOCTL_RADXA_PLATFORM_SVC_FAN_GET_STATE \
    CTL_CODE(RADXA_PLATFORM_TYPE, 0xA49, METHOD_BUFFERED, FILE_READ_ACCESS)
#define IOCTL_RADXA_PLATFORM_SVC_FAN_GET_CONTROL \
    CTL_CODE(RADXA_PLATFORM_TYPE, 0xA4A, METHOD_BUFFERED, FILE_READ_ACCESS)
#define IOCTL_RADXA_PLATFORM_SVC_FAN_SET_CONTROL \
    CTL_CODE(RADXA_PLATFORM_TYPE, 0xA4B, METHOD_BUFFERED, FILE_WRITE_ACCESS)
#define IOCTL_RADXA_PLATFORM_SVC_ENUM_SENSORS \
    CTL_CODE(RADXA_PLATFORM_TYPE, 0xA4C, METHOD_BUFFERED, FILE_READ_ACCESS)
#define IOCTL_RADXA_PLATFORM_SVC_READ_SENSOR \
    CTL_CODE(RADXA_PLATFORM_TYPE, 0xA4D, METHOD_BUFFERED, FILE_READ_ACCESS)

#pragma pack(push, 8)

typedef struct _RADXA_SVC_STRUCT_HEADER
{
    UINT32 Size;
    UINT32 Version;
} RADXA_SVC_STRUCT_HEADER;

typedef struct _RADXA_SVC_INTERFACE_INFO
{
    RADXA_SVC_STRUCT_HEADER Header;
    UINT32 State;
    INT32 LastServiceStatus;
    UINT16 ServiceMajor;
    UINT16 ServiceMinor;
    UINT32 Capabilities;
    UINT32 RequiredCapabilities;
    UINT32 MissingCapabilities;
    UINT32 Reserved[2];
    UINT64 TxCount;
    UINT64 RxCount;
    UINT64 TimeoutCount;
    UINT64 BadMessageCount;
    UINT64 DroppedMessageCount;
} RADXA_SVC_INTERFACE_INFO;

typedef struct _RADXA_SVC_PING_RESULT
{
    RADXA_SVC_STRUCT_HEADER Header;
    UINT32 Pong;
    UINT16 ServiceMajor;
    UINT16 ServiceMinor;
} RADXA_SVC_PING_RESULT;

typedef struct _RADXA_SVC_VERSION_INFO
{
    RADXA_SVC_STRUCT_HEADER Header;
    UINT16 ServiceMajor;
    UINT16 ServiceMinor;
    UINT32 Capabilities;
} RADXA_SVC_VERSION_INFO;

typedef struct _RADXA_SVC_PROFILE_INFO
{
    RADXA_SVC_STRUCT_HEADER Header;
    UINT32 EffectiveProfile;
    UINT32 ServiceProfile;
    UINT32 FanControlMode;
    UINT32 Reserved;
} RADXA_SVC_PROFILE_INFO;

typedef struct _RADXA_SVC_SET_PROFILE_REQUEST
{
    RADXA_SVC_STRUCT_HEADER Header;
    UINT32 Profile;
    UINT32 Reserved;
} RADXA_SVC_SET_PROFILE_REQUEST;

typedef struct _RADXA_SVC_LOG_RESULT
{
    RADXA_SVC_STRUCT_HEADER Header;
    UINT32 BytesValid;
    UINT32 Reserved;
    UINT8 Data[RADXA_SVC_MAX_LOG_SIZE];
} RADXA_SVC_LOG_RESULT;

typedef struct _RADXA_SVC_PWM_INFO
{
    RADXA_SVC_STRUCT_HEADER Header;
    UINT32 ChannelCount;
    UINT32 SupportedMask;
    UINT32 DefaultChannel;
    UINT32 MinimumPeriodNanoseconds;
    UINT32 MaximumPeriodNanoseconds;
    UINT32 Reserved;
} RADXA_SVC_PWM_INFO;

typedef struct _RADXA_SVC_PWM_APPLY_REQUEST
{
    RADXA_SVC_STRUCT_HEADER Header;
    UINT32 Channel;
    UINT32 Enable;
    UINT32 PeriodNanoseconds;
    UINT32 DutyNanoseconds;
} RADXA_SVC_PWM_APPLY_REQUEST;

typedef struct _RADXA_SVC_PWM_STATE_REQUEST
{
    RADXA_SVC_STRUCT_HEADER Header;
    UINT32 Channel;
    UINT32 Reserved;
} RADXA_SVC_PWM_STATE_REQUEST;

typedef struct _RADXA_SVC_PWM_STATE
{
    RADXA_SVC_STRUCT_HEADER Header;
    UINT32 Channel;
    UINT32 Enabled;
    UINT32 PeriodNanoseconds;
    UINT32 DutyNanoseconds;
    UINT32 ActualPeriodNanoseconds;
    UINT32 ActualDutyNanoseconds;
    UINT32 PwmValue;
    UINT32 Reserved;
} RADXA_SVC_PWM_STATE;

typedef struct _RADXA_SVC_FAN_STATE
{
    RADXA_SVC_STRUCT_HEADER Header;
    UINT32 Profile;
    UINT32 Running;
    UINT32 Emergency;
    UINT32 CpuValid;
    UINT32 CpuStaleTicks;
    INT32 CpuTemperatureDeciCelsius;
    UINT32 GpuValid;
    UINT32 GpuStaleTicks;
    INT32 GpuTemperatureDeciCelsius;
    UINT32 CurrentDutyNanoseconds;
    UINT32 TargetDutyNanoseconds;
    UINT32 PwmChannel;
    UINT32 PwmPeriodNanoseconds;
    UINT32 LoopCount;
    UINT32 FaultCount;
    INT32 LastStatus;
    UINT32 ControlMode;
    UINT32 ManualPwm;
    UINT32 ControlFieldsValid;
    UINT32 Reserved;
} RADXA_SVC_FAN_STATE;

typedef struct _RADXA_SVC_FAN_CONTROL
{
    RADXA_SVC_STRUCT_HEADER Header;
    UINT32 ControlMode;
    UINT32 ManualPwm;
} RADXA_SVC_FAN_CONTROL;

typedef struct _RADXA_SVC_SENSOR_DESCRIPTOR
{
    UINT32 SensorId;
    UINT32 SensorType;
    CHAR Name[RADXA_SVC_SENSOR_NAME_LENGTH];
} RADXA_SVC_SENSOR_DESCRIPTOR;

typedef struct _RADXA_SVC_SENSOR_LIST
{
    RADXA_SVC_STRUCT_HEADER Header;
    UINT32 SensorCount;
    UINT32 Reserved;
    RADXA_SVC_SENSOR_DESCRIPTOR Sensors[RADXA_SVC_MAX_SENSORS];
} RADXA_SVC_SENSOR_LIST;

typedef struct _RADXA_SVC_SENSOR_READ_REQUEST
{
    RADXA_SVC_STRUCT_HEADER Header;
    UINT32 SensorId;
    UINT32 Reserved;
} RADXA_SVC_SENSOR_READ_REQUEST;

typedef struct _RADXA_SVC_SENSOR_READING
{
    RADXA_SVC_STRUCT_HEADER Header;
    UINT32 SensorId;
    UINT32 SensorType;
    UINT32 ValidMask;
    INT32 TemperatureMilliCelsius;
    INT32 VoltageMillivolts;
    UINT32 Reserved;
    INT64 CurrentMilliamps;
    INT64 PowerMicrowatts;
} RADXA_SVC_SENSOR_READING;

#pragma pack(pop)

#if defined(__cplusplus)
#define RADXA_SVC_STATIC_ASSERT(_expression) static_assert((_expression), #_expression)
#else
#define RADXA_SVC_STATIC_ASSERT(_expression) C_ASSERT(_expression)
#endif

#define RADXA_SVC_IOCTL_FUNCTION(_code) ((((UINT32)(_code)) >> 2) & 0xFFFu)
#define RADXA_SVC_IOCTL_ACCESS(_code)   ((((UINT32)(_code)) >> 14) & 0x3u)
#define RADXA_SVC_IOCTL_METHOD(_code)   (((UINT32)(_code)) & 0x3u)

RADXA_SVC_STATIC_ASSERT(sizeof(RADXA_SVC_STRUCT_HEADER) == 8);
RADXA_SVC_STATIC_ASSERT(sizeof(RADXA_SVC_INTERFACE_INFO) == 80);
RADXA_SVC_STATIC_ASSERT(sizeof(RADXA_SVC_PING_RESULT) == 16);
RADXA_SVC_STATIC_ASSERT(sizeof(RADXA_SVC_VERSION_INFO) == 16);
RADXA_SVC_STATIC_ASSERT(sizeof(RADXA_SVC_PROFILE_INFO) == 24);
RADXA_SVC_STATIC_ASSERT(sizeof(RADXA_SVC_SET_PROFILE_REQUEST) == 16);
RADXA_SVC_STATIC_ASSERT(sizeof(RADXA_SVC_LOG_RESULT) == 2064);
RADXA_SVC_STATIC_ASSERT(sizeof(RADXA_SVC_PWM_INFO) == 32);
RADXA_SVC_STATIC_ASSERT(sizeof(RADXA_SVC_PWM_APPLY_REQUEST) == 24);
RADXA_SVC_STATIC_ASSERT(sizeof(RADXA_SVC_PWM_STATE_REQUEST) == 16);
RADXA_SVC_STATIC_ASSERT(sizeof(RADXA_SVC_PWM_STATE) == 40);
RADXA_SVC_STATIC_ASSERT(sizeof(RADXA_SVC_FAN_STATE) == 88);
RADXA_SVC_STATIC_ASSERT(sizeof(RADXA_SVC_FAN_CONTROL) == 16);
RADXA_SVC_STATIC_ASSERT(sizeof(RADXA_SVC_SENSOR_DESCRIPTOR) == 40);
RADXA_SVC_STATIC_ASSERT(sizeof(RADXA_SVC_SENSOR_LIST) == 2576);
RADXA_SVC_STATIC_ASSERT(sizeof(RADXA_SVC_SENSOR_READ_REQUEST) == 16);
RADXA_SVC_STATIC_ASSERT(sizeof(RADXA_SVC_SENSOR_READING) == 48);

RADXA_SVC_STATIC_ASSERT(RADXA_SVC_IOCTL_FUNCTION(IOCTL_RADXA_PLATFORM_SVC_GET_INTERFACE_INFO) == 0xA40u);
RADXA_SVC_STATIC_ASSERT(RADXA_SVC_IOCTL_FUNCTION(IOCTL_RADXA_PLATFORM_SVC_PING) == 0xA41u);
RADXA_SVC_STATIC_ASSERT(RADXA_SVC_IOCTL_FUNCTION(IOCTL_RADXA_PLATFORM_SVC_GET_SERVICE_VERSION) == 0xA42u);
RADXA_SVC_STATIC_ASSERT(RADXA_SVC_IOCTL_FUNCTION(IOCTL_RADXA_PLATFORM_SVC_GET_PROFILE) == 0xA43u);
RADXA_SVC_STATIC_ASSERT(RADXA_SVC_IOCTL_FUNCTION(IOCTL_RADXA_PLATFORM_SVC_SET_PROFILE) == 0xA44u);
RADXA_SVC_STATIC_ASSERT(RADXA_SVC_IOCTL_FUNCTION(IOCTL_RADXA_PLATFORM_SVC_GET_LOG) == 0xA45u);
RADXA_SVC_STATIC_ASSERT(RADXA_SVC_IOCTL_FUNCTION(IOCTL_RADXA_PLATFORM_SVC_PWM_GET_INFO) == 0xA46u);
RADXA_SVC_STATIC_ASSERT(RADXA_SVC_IOCTL_FUNCTION(IOCTL_RADXA_PLATFORM_SVC_PWM_APPLY) == 0xA47u);
RADXA_SVC_STATIC_ASSERT(RADXA_SVC_IOCTL_FUNCTION(IOCTL_RADXA_PLATFORM_SVC_PWM_GET_STATE) == 0xA48u);
RADXA_SVC_STATIC_ASSERT(RADXA_SVC_IOCTL_FUNCTION(IOCTL_RADXA_PLATFORM_SVC_FAN_GET_STATE) == 0xA49u);
RADXA_SVC_STATIC_ASSERT(RADXA_SVC_IOCTL_FUNCTION(IOCTL_RADXA_PLATFORM_SVC_FAN_GET_CONTROL) == 0xA4Au);
RADXA_SVC_STATIC_ASSERT(RADXA_SVC_IOCTL_FUNCTION(IOCTL_RADXA_PLATFORM_SVC_FAN_SET_CONTROL) == 0xA4Bu);
RADXA_SVC_STATIC_ASSERT(RADXA_SVC_IOCTL_FUNCTION(IOCTL_RADXA_PLATFORM_SVC_ENUM_SENSORS) == 0xA4Cu);
RADXA_SVC_STATIC_ASSERT(RADXA_SVC_IOCTL_FUNCTION(IOCTL_RADXA_PLATFORM_SVC_READ_SENSOR) == 0xA4Du);

RADXA_SVC_STATIC_ASSERT(RADXA_SVC_IOCTL_METHOD(IOCTL_RADXA_PLATFORM_SVC_GET_INTERFACE_INFO) == METHOD_BUFFERED);
RADXA_SVC_STATIC_ASSERT(RADXA_SVC_IOCTL_METHOD(IOCTL_RADXA_PLATFORM_SVC_FAN_SET_CONTROL) == METHOD_BUFFERED);
RADXA_SVC_STATIC_ASSERT(RADXA_SVC_IOCTL_METHOD(IOCTL_RADXA_PLATFORM_SVC_READ_SENSOR) == METHOD_BUFFERED);
RADXA_SVC_STATIC_ASSERT(RADXA_SVC_IOCTL_ACCESS(IOCTL_RADXA_PLATFORM_SVC_GET_INTERFACE_INFO) == FILE_READ_ACCESS);
RADXA_SVC_STATIC_ASSERT(RADXA_SVC_IOCTL_ACCESS(IOCTL_RADXA_PLATFORM_SVC_PING) == FILE_READ_ACCESS);
RADXA_SVC_STATIC_ASSERT(RADXA_SVC_IOCTL_ACCESS(IOCTL_RADXA_PLATFORM_SVC_GET_SERVICE_VERSION) == FILE_READ_ACCESS);
RADXA_SVC_STATIC_ASSERT(RADXA_SVC_IOCTL_ACCESS(IOCTL_RADXA_PLATFORM_SVC_GET_PROFILE) == FILE_READ_ACCESS);
RADXA_SVC_STATIC_ASSERT(RADXA_SVC_IOCTL_ACCESS(IOCTL_RADXA_PLATFORM_SVC_SET_PROFILE) == FILE_WRITE_ACCESS);
RADXA_SVC_STATIC_ASSERT(RADXA_SVC_IOCTL_ACCESS(IOCTL_RADXA_PLATFORM_SVC_GET_LOG) == FILE_READ_ACCESS);
RADXA_SVC_STATIC_ASSERT(RADXA_SVC_IOCTL_ACCESS(IOCTL_RADXA_PLATFORM_SVC_PWM_GET_INFO) == FILE_READ_ACCESS);
RADXA_SVC_STATIC_ASSERT(RADXA_SVC_IOCTL_ACCESS(IOCTL_RADXA_PLATFORM_SVC_PWM_APPLY) == FILE_WRITE_ACCESS);
RADXA_SVC_STATIC_ASSERT(RADXA_SVC_IOCTL_ACCESS(IOCTL_RADXA_PLATFORM_SVC_PWM_GET_STATE) == FILE_READ_ACCESS);
RADXA_SVC_STATIC_ASSERT(RADXA_SVC_IOCTL_ACCESS(IOCTL_RADXA_PLATFORM_SVC_FAN_GET_STATE) == FILE_READ_ACCESS);
RADXA_SVC_STATIC_ASSERT(RADXA_SVC_IOCTL_ACCESS(IOCTL_RADXA_PLATFORM_SVC_FAN_GET_CONTROL) == FILE_READ_ACCESS);
RADXA_SVC_STATIC_ASSERT(RADXA_SVC_IOCTL_ACCESS(IOCTL_RADXA_PLATFORM_SVC_FAN_SET_CONTROL) == FILE_WRITE_ACCESS);
RADXA_SVC_STATIC_ASSERT(RADXA_SVC_IOCTL_ACCESS(IOCTL_RADXA_PLATFORM_SVC_ENUM_SENSORS) == FILE_READ_ACCESS);
RADXA_SVC_STATIC_ASSERT(RADXA_SVC_IOCTL_ACCESS(IOCTL_RADXA_PLATFORM_SVC_READ_SENSOR) == FILE_READ_ACCESS);
